export const testimonials = [
  {
    name: "Anna Aaker",
    location: "Oslo, Norway",
    text: "Utulivu Tours made my safari unforgettable! The guides were knowledgeable, and the views of the Serengeti were breathtaking.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=5",
  },
  {
    name: "Liam Patel",
    location: "Paris, France",
    text: "A perfect blend of adventure and relaxation. The Zanzibar beach trip was paradise!",
    rating: 4,
    avatar: "https://i.pravatar.cc/150?img=68",
  },
  {
    name: "Aina Singh",
    location: "Mumbai, India",
    text: "The Ngorongoro Crater wildlife tour exceeded expectations. Saw the Big Five up close—highly recommend!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150? 이제=58",
  },
  {
    name: "Martin Gonzalez",
    location: "Madrid, Spain",
    text: "Immersing in Maasai culture was enlightening. The village stay and stories around the fire were magical.",
    rating: 4,
    avatar: "https://i.pravatar.cc/150?img=3",
  },
  {
    name: "John Kim",
    location: "Seoul, South Korea",
    text: "Hiking in the Usambara Mountains was exhilarating. Stunning views and eco-friendly guides made it perfect.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=12",
  },
  {
    name: "Elena Rossi",
    location: "Rome, Italy",
    text: "Birdwatching in Tarangire National Park was a highlight. Spotted over 50 species—Utulivu's experts made it educational and fun!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=1",
  },
  {
    name: "Adunni Adewale",
    location: "Lagos, Nigeria",
    text: "Family safari in Serengeti was safe and exciting for kids. The hot air balloon ride at dawn was magical!",
    rating: 4,
    avatar: "https://i.pravatar.cc/150?img=16",
  },
  {
    name: "Anna Leclerc",
    location: "Toronto, Canada",
    text: "Photography workshop in Lake Manyara—captured stunning flamingo flocks. Professional tips elevated my skills.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    name: "Isabella Chen",
    location: "Sydney, Australia",
    text: "The Selous Game Reserve boat safari was thrilling. Saw hippos and crocodiles up close in their natural habitat!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=7",
  },
  {
    name: "Olivia Thompson",
    location: "London, UK",
    text: "Exploring Ruaha National Park's rugged beauty was an adventure. Utulivu's off-the-beaten-path routes were spot on.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=9",
  },
  {
    name: "Zoe Nkosi",
    location: "Johannesburg, South Africa",
    text: "Cultural homestay in a local village opened my eyes to Tanzanian traditions. Warm hospitality and delicious food!",
    rating: 4,
    avatar: "https://i.pravatar.cc/150?img=10",
  },
  {
    name: "Noah Williams",
    location: "New York, USA",
    text: "Diving in Mafia Island's coral reefs was mesmerizing. Utulivu arranged everything seamlessly.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=8",
  },
  {
    name: "Lorenzo Hassan",
    location: "Cairo, Egypt",
    text: "Sunset dhow cruise in Zanzibar Stone Town—romantic and picturesque. A highlight of my trip!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=11",
  },
  {
    name: "Emma Larsson",
    location: "Stockholm, Sweden",
    text: "Trekking in the Ngorongoro Highlands offered fresh air and stunning vistas. Guides shared fascinating geology insights.",
    rating: 4,
    avatar: "https://i.pravatar.cc/150?img=15",
  },
  {
    name: "Santiago Ramirez",
    location: "Mexico City, Mexico",
    text: "Volunteering at a community project in Arusha was rewarding. Utulivu connected me with meaningful local impact.",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=14",
  },
  {
    name: "Tom Andersson",
    location: "Copenhagen, Denmark",
    text: "Hot springs and coffee plantation tour near Moshi—relaxing and aromatic. Perfect day trip!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=17",
  },
  {
    name: "Amara Diallo",
    location: "Dakar, Senegal",
    text: "Witnessing the Great Migration in Serengeti was life-changing. Utulivu timed it perfectly!",
    rating: 5,
    avatar: "https://i.pravatar.cc/150?img=18",
  },
];
